"""Create reset_passwords table

Revision ID: 1632b03755c3
Revises: a00c73bafccb
Create Date: 2024-12-12 12:07:00.574716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1632b03755c3"
down_revision: Union[str, None] = "a00c73bafccb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic -adjust by me ###
    op.create_table(
        "reset_passwords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Used", "Pending", name="codestatus"),
            server_default="Pending",
            nullable=True,
        ),
        sa.Column(
            "created_on",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        None, "errors", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic -adjust by me ###
    op.drop_constraint(None, "errors", type_="foreignkey")
    op.drop_table("reset_passwords")
    # ### end Alembic commands ###
