"""Create users table

Revision ID: dadea625dccd
Revises: 
Create Date: 2024-12-10 20:19:40.561370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dadea625dccd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic -adjust by me ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("gender", sa.Enum("Male", "Female", name="gender"), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Active", "Inactive", name="accountstatus"),
            server_default="Active",
            nullable=True,
        ),
        sa.Column(
            "created_on",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic -adjust by me ###
    op.drop_table("users")
    # ### end Alembic commands ###
